### PR TITLE
remove image-framed-light

### PR DESCRIPTION
**Pull request by sunnymsf**
## What does this PR do?

Removes **image-framed-light** in VSCode preview and VSCode Intellisense

[W-13730174](https://gus.lightning.force.com/a07EE00001VikDQYAZ)

## Screenshots
No border for the second image in VSCode preview
Screenshot 2023-10-30 at 9 56 43 AM

No class suggestion
Screenshot 2023-10-30 at 9 50 22 AM

### CODE REVIEW

**Comment by LokeshNSF** [comment]
Do we always need a border?

**Review by LokeshNSF — APPROVED** [review]
LGTM!

**Comment by sunnymsf** [comment]
> Do we always need a border?

We used to have a border always for SFDocs images. We removed that now as part of [this](https://github.com/salesforcedevs/developer-website/pull/2215/files) PR.

Now whoever needs a border, needs to use the **image-framed** class.

**Comment by sunnymsf** [comment]
@KishoreNemalipuri @PrabhavSF merging this PR. 

Nothing urgent I feel, but please publish the latest versions to market place whenever you can. Thanks!

**Pull request merged**
